[project]
name = "image-conv"
version = "0.1.0"
description = "Study project realizing image convolution"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib==3.10.9",
    "numba==0.65.0",
    "numpy==2.4.4",
    "opencv-python==4.13.0.92",
    "pandas==3.0.2",
    "pillow==12.2.0",
    "pytest==9.0.2",
    "pytest-benchmark==5.2.3",
    "seaborn==0.13.2",
]
[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "N"]

[tool.mypy]
python_version = "3.12"
strict = true
ignore_missing_imports = true
disallow_untyped_decorators = false
